----
title: "Correlatinon global (Stanford) mutation frequencies with frequencies obtained by other studies "
version: "May 2016"
author: "Kristof Theys, Marion Hartl, Pleuni Pennings"
output: html_document
----

# Output as end result 

Please go to the end for the official results 

### Read in frequency values from Stanford

```{r}
stanford_threshold <-read.csv('../Output/freqPatTs_Stanford.csv')
```

### Read in mean frequency values from other datasets
```{r}
lehman_threshold_mean<-read.csv('../Output/OverviewSelCoeffLehman.csv')
zanini_threshold_mean<-read.csv('../Output/OverviewSelCoeffZanini.csv')
bacheler_threshold_mean<-read.csv('../Output/OverviewSelCoeff_Bacheler.csv')
```

### Comparison of frequencies between Stanford and different datasets  (internal use)

```{r}
for (compare_dataset in list(bacheler_threshold_mean,zanini_threshold_mean,lehman_threshold_mean))
  {

# identify the column with the frequency values   
compare_dataset_colmeans<-names(compare_dataset)[grep('colM',names(compare_dataset))]

#remove first 13 amino acid  positions of protease
stanford_compare<-cbind(stanford_threshold,compare_dataset)
#remove stop and res positions 
stanford_compare_14<-stanford_compare[40:nrow(stanford_compare),]
stanford_compare_14_stopres<-stanford_compare_14[stanford_compare_14$TypeOfSite!='res' & stanford_compare_14$TypeOfSite!='stop' ,]
stanford_compare_14_stopres$TypeOfSite<-factor(stanford_compare_14_stopres$TypeOfSite)
stanford_compare_14_stopres$TypeOfSite<-relevel(stanford_compare_14_stopres$TypeOfSite,"syn")
# color setting for plot 
#66C2A5 is green    ==> should be for synonymous 
#FC8D62 is red
library(RColorBrewer)
cols_all <- brewer.pal(nlevels(stanford_compare_14_stopres$TypeOfSite),"Set2")



# plot and calculatecorrelation coefficient for all positions 
plot(stanford_compare_14_stopres[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres))],stanford_compare_14_stopres$colMeansTs0_stanford,ylab="Between-patient",xlab="Within-patient", col=cols_all[stanford_compare_14_stopres$TypeOfSite],lwd=2,main= paste("Stanford_vs_",compare_dataset_colmeans,sep=""))
legend('topleft', legend = levels(stanford_compare_14_stopres$TypeOfSite), col = cols_all, cex = 0.8, pch = 1)
text(0.4,0.6,paste("R-squared=",round(cor.test(stanford_compare_14_stopres$colMeansTs0_stanford,stanford_compare_14_stopres[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres))])$estimate*cor.test(stanford_compare_14_stopres$colMeansTs0_stanford,stanford_compare_14_stopres[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres))])$estimate,3)))

# plot and correlation coefficient for all positions but LOG10 transformed to plot, not for the corr coef
plot(log10(stanford_compare_14_stopres[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres))]+0.0001),log10(stanford_compare_14_stopres$colMeansTs0_stanford+0.0001),ylab="Between-patient",xlab="Within-patient", col=cols_all[stanford_compare_14_stopres$TypeOfSite],lwd=2,main= paste("log10: Stanford_vs_",compare_dataset_colmeans,sep=""),xaxt = "n",yaxt = "n")
axis(1,at=(0:-4),c(0,expression(paste("10"^"-1")),expression(paste("10"^"-2")),expression(paste("10"^"-3")),expression(paste("10"^"-4"))))
axis(2,at=(0:-4),c(0,expression(paste("10"^"-1")),expression(paste("10"^"-2")),expression(paste("10"^"-3")),expression(paste("10"^"-4"))),las=2)
text(-2,-0.5,paste("R-squared=",
round(cor.test(stanford_compare_14_stopres[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres))],stanford_compare_14_stopres$colMeansTs0_stanford)$estimate * cor.test(stanford_compare_14_stopres[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres))],stanford_compare_14_stopres$colMeansTs0_stanford)$estimate,3)))
legend('topleft', legend = levels(stanford_compare_14_stopres$TypeOfSite), col = cols_all, cex = 0.8, pch = 1)

# ONLY SYN  
stanford_compare_14_stopres_syn<-stanford_compare_14_stopres[stanford_compare_14_stopres$TypeOfSite=='syn',]
plot(stanford_compare_14_stopres_syn[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres_syn))],stanford_compare_14_stopres_syn$colMeansTs0_stanford,xlab=compare_dataset_colmeans,ylab='Stanford', col=cols_all[stanford_compare_14_stopres_syn$TypeOfSite],lwd=2,main= paste("SYN:Stanford_vs_",compare_dataset_colmeans,sep=""))
text(0.4,0.4,paste("R-squared=",round(cor.test(stanford_compare_14_stopres_syn$colMeansTs0_stanford,stanford_compare_14_stopres_syn[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres_syn))])$estimate*cor.test(stanford_compare_14_stopres_syn$colMeansTs0_stanford,stanford_compare_14_stopres_syn[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres_syn))])$estimate,3)))

# ONLY NON-SYN 
stanford_compare_14_stopres_nonsyn<-stanford_compare_14_stopres[stanford_compare_14_stopres$TypeOfSite=='nonsyn',]
plot(stanford_compare_14_stopres_nonsyn[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres_nonsyn))],stanford_compare_14_stopres_nonsyn$colMeansTs0_stanford,xlab=compare_dataset_colmeans,ylab='Stanford', col=cols_all[stanford_compare_14_stopres_nonsyn$TypeOfSite],lwd=2, main=paste("NONSYN:Stanford_vs_",compare_dataset_colmeans,sep=""))
text(0.4,0.4,paste("R-squared=",round(cor.test(stanford_compare_14_stopres_nonsyn$colMeansTs0_stanford,stanford_compare_14_stopres_nonsyn[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres_nonsyn))])$estimate*cor.test(stanford_compare_14_stopres_nonsyn$colMeansTs0_stanford,stanford_compare_14_stopres_nonsyn[,match(compare_dataset_colmeans,names(stanford_compare_14_stopres_nonsyn))])$estimate,3)))
}
```


## Official figure:Bacheler and Stanford, shown as normal and log transformed. 
```{r}
library(plotrix)
# making the data frame bacheler and stanford 
stanford_bacheler<-cbind(stanford_threshold,bacheler_threshold_mean)
#remove stop and res positions 
stanford_bacheler_14<-stanford_bacheler[40:nrow(stanford_bacheler),]
stanford_bacheler_14_stopres<-stanford_bacheler_14[stanford_bacheler_14$TypeOfSite!='res' & stanford_bacheler_14$TypeOfSite!='stop' ,]
stanford_bacheler_14_stopres$TypeOfSite<-factor(stanford_bacheler_14_stopres$TypeOfSite)
stanford_bacheler_14_stopres$TypeOfSite<-relevel(stanford_bacheler_14_stopres$TypeOfSite,"syn")


# plot with non-transformd  values 
par(mar = c(7,5,4,2) + 0.3)
plot(stanford_bacheler_14_stopres$colMeansTs0,stanford_bacheler_14_stopres$colMeansTs0_stanford,ylab="Between-patient",xlab="Within-patient", col=cols_all[stanford_bacheler_14_stopres$TypeOfSite],lwd=2,main= "Within-patient vs between-patient frequencies")
text(median(axTicks(1)),mean(tail(axTicks(2),2)),paste("R-squared=",round(cor.test(stanford_bacheler_14_stopres$colMeansTs0,stanford_bacheler_14_stopres$colMeansTs0_stanford)$estimate * cor.test(stanford_bacheler_14_stopres$colMeansTs0,stanford_bacheler_14_stopres$colMeansTs0_stanford)$estimate,3)))
legend('topleft', legend = levels(stanford_bacheler_14_stopres$TypeOfSite), col = cols_all, cex = 0.8, pch = 1)


# plot with log 10 transformd  values, corr coef calculated on non-log transformed values 
#pdf('../Output/comparison_stanford_vs_bacher_axes.pdf')
plot(log10(stanford_bacheler_14_stopres$colMeansTs0+0.0001),log10(stanford_bacheler_14_stopres$colMeansTs0_stanford+0.0001),ylab="Between-patient",xlab="Within-patient", col=cols_all[stanford_bacheler_14_stopres$TypeOfSite],lwd=2,xaxt = "n",yaxt = "n",cex.lab=1.2,cex.main =1.3)
axis(1,at=(0:-4),c(1,expression(paste("10"^"-1")),expression(paste("10"^"-2")),expression(paste("10"^"-3")),expression(paste("0"))),cex.axis = 1.2)
axis(2,at=(0:-4),c(1,expression(paste("10"^"-1")),expression(paste("10"^"-2")),expression(paste("10"^"-3")),expression(paste("0"))),las=2,cex.axis =1.2)
axis.break(axis=2,breakpos=-3.92,bgcol="white",breakcol="black",style="slash",brw=0.01)
axis.break(axis=1,breakpos=-3.92,bgcol="white",breakcol="black",style="slash",brw=0.01)
text(median(axTicks(1)),mean(tail(axTicks(2),2)),paste("R-squared=",round(cor.test(stanford_bacheler_14_stopres$colMeansTs0,stanford_bacheler_14_stopres$colMeansTs0_stanford)$estimate * cor.test(stanford_bacheler_14_stopres$colMeansTs0,stanford_bacheler_14_stopres$colMeansTs0_stanford)$estimate,3)),cex=1)
#dev.off()

# plot with log 10 transformd  values, corr coef calculated on non-log transformed values 
# same figures as the one above but using the 'log= 'yx' parameter 
par(mar = c(7,5,4,2) + 0.1)
plot(stanford_bacheler_14_stopres$colMeansTs0+0.0001,stanford_bacheler_14_stopres$colMeansTs0_stanford+0.0001, log='xy',ylab="Between-patient",xlab="Within-patient", col=cols_all[stanford_bacheler_14_stopres$TypeOfSite],lwd=2,main= "Within-patient vs between-patient frequencies",xaxt = "n",yaxt = "n")
axis(1,at=axTicks(1),c(0,expression(paste("10"^"-1")),expression(paste("10"^"-2")),expression(paste("10"^"-3")),expression(paste("10"^"-4"))))
axis(2,at=axTicks(1),c(0,expression(paste("10"^"-1")),expression(paste("10"^"-2")),expression(paste("10"^"-3")),expression(paste("10"^"-4"))),las=2)
text(median(axTicks(1)),mean(tail(axTicks(2),2)),paste("R-squared=",
round(cor.test(stanford_bacheler_14_stopres$colMeansTs0,stanford_bacheler_14_stopres$colMeansTs0_stanford)$estimate * cor.test(stanford_bacheler_14_stopres$colMeansTs0,stanford_bacheler_14_stopres$colMeansTs0_stanford)$estimate,3)
))
```








